# Base configs
baseurl: "https://khaleefaz.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Khaleefaz ⚔️"
subtitle: "Photo Gallery"
author: "Mohammed Ashad"
header:
 title: "Khaleefaz ⚔️"
 subtitle: "Photo Gallery"
footer:
 name: "Hey there, my name is Mohammed Ashad"
 bio: "This is a photo gallery of AKNM Gov. Polutechnic College Chelary Electronics engineering 2k18-21"
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
  
plugins:
  - jekyll-sitemap
