# Base configs
baseurl: "https://khaleefaz.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Khaleefaz ⚔️"
subtitle: "Photo Gallery"
author: "Mohammed Ashad"
header:
 title: "Khaleefaz ⚔️"
 subtitle: "Photo Gallery"
footer:
 name: "Hey there, I am Mohammed Ashad"
 bio: "This is a photo gallery of AKNM Gov. Polutechnic College Chelary Electronics engineering 2k18-21"
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://instagram.com/khaleefazzz"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/khaleefaz"
  
plugins:
  - jekyll-sitemap
